server:
  host: localhost
  port: 8087
  db: car_stock_db

spring:
  application:
    name: stock-service
  banner:
    location: banner.txt
  config:
    import: eureka.yml,info.yml
  jpa:
    show-sql: false
    hibernate.ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.format_sql: true
  data:
    jpa:
      repositories:
        enabled: true
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:mysql://${server.host}:3306/${server.db}
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 60000
      max-lifetime: 2000000
      connection-timeout: 60000
      pool-name: carConnectionPool
    driver-class-name: com.mysql.cj.jdbc.Driver

grpc:
  server:
    port: 9090